import { useState } from 'react';
import { Download, FileJson, FileText, Loader2, Check } from 'lucide-react';
import jsPDF from 'jspdf';

const ExportButton = ({ data }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [exporting, setExporting] = useState(null);

  const exportToJSON = () => {
    setExporting('json');
    
    try {
      const jsonStr = JSON.stringify(data, null, 2);
      const blob = new Blob([jsonStr], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `gitsoar-analysis-${data.profile.username}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Export error:', error);
      alert('Failed to export JSON. Please try again.');
    } finally {
      setTimeout(() => {
        setExporting(null);
        setIsOpen(false);
      }, 500);
    }
  };

  const exportToPDF = () => {
    setExporting('pdf');
    
    try {
      const doc = new jsPDF();
      const { profile, scores, analysis, stats } = data;
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(37, 99, 235);
      doc.text('GitSoar Analysis Report', 20, 30);
      
      // Profile Info
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text(`Profile: @${profile.username}`, 20, 50);
      
      if (profile.name) {
        doc.text(`Name: ${profile.name}`, 20, 60);
      }
      
      // Overall Score
      doc.setFontSize(18);
      doc.setTextColor(37, 99, 235);
      doc.text(`Overall Score: ${scores.overall}/100`, 20, 80);
      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Rating: ${scores.rating.label}`, 20, 90);
      
      // Stats
      doc.setFontSize(14);
      doc.text('Statistics:', 20, 110);
      doc.setFontSize(11);
      doc.text(`Total Repositories: ${stats.totalRepos}`, 25, 120);
      doc.text(`Original Repositories: ${stats.originalRepos}`, 25, 128);
      doc.text(`Total Stars: ${stats.totalStars}`, 25, 136);
      doc.text(`Total Forks: ${stats.totalForks}`, 25, 144);
      doc.text(`Languages: ${stats.languages}`, 25, 152);
      
      // Dimension Scores
      doc.setFontSize(14);
      doc.text('Dimension Scores:', 20, 170);
      doc.setFontSize(11);
      
      const dimensions = [
        ['Documentation Quality', scores.dimensions.documentation],
        ['Code Structure', scores.dimensions.structure],
        ['Activity Consistency', scores.dimensions.activity],
        ['Repository Organization', scores.dimensions.organization],
        ['Project Impact', scores.dimensions.impact],
        ['Technical Depth', scores.dimensions.technical]
      ];
      
      let yPos = 180;
      dimensions.forEach(([name, score]) => {
        doc.text(`${name}: ${score}/100`, 25, yPos);
        yPos += 8;
      });
      
      // Recommendations
      if (analysis.recommendations.length > 0) {
        doc.addPage();
        doc.setFontSize(18);
        doc.setTextColor(37, 99, 235);
        doc.text('Top Recommendations', 20, 30);
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        
        yPos = 45;
        analysis.recommendations.slice(0, 5).forEach((rec, index) => {
          const lines = doc.splitTextToSize(`${index + 1}. ${rec.title}: ${rec.description}`, 170);
          doc.text(lines, 20, yPos);
          yPos += lines.length * 6 + 5;
          
          if (yPos > 270) {
            doc.addPage();
            yPos = 30;
          }
        });
      }
      
      // Footer
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by GitSoar - ${new Date().toLocaleDateString()}`, 20, 290);
        doc.text(`Page ${i} of ${pageCount}`, 170, 290);
      }
      
      doc.save(`gitsoar-report-${profile.username}.pdf`);
    } catch (error) {
      console.error('PDF export error:', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setTimeout(() => {
        setExporting(null);
        setIsOpen(false);
      }, 500);
    }
  };

  return (
    <div className="relative">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="btn-secondary"
      >
        <Download className="w-4 h-4 mr-2" />
        Export Report
      </button>
      
      {isOpen && (
        <>
          <div
            className="fixed inset-0 z-10"
            onClick={() => setIsOpen(false)}
          />
          <div className="absolute right-0 mt-2 w-56 bg-white rounded-xl shadow-xl border border-gray-200 z-20 overflow-hidden">
            <button
              onClick={exportToJSON}
              disabled={exporting !== null}
              className="w-full px-4 py-3 flex items-center space-x-3 hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              {exporting === 'json' ? (
                <Loader2 className="w-5 h-5 text-primary-600 animate-spin" />
              ) : (
                <FileJson className="w-5 h-5 text-primary-600" />
              )}
              <div className="text-left">
                <p className="font-medium text-gray-900">Export JSON</p>
                <p className="text-xs text-gray-500">Raw analysis data</p>
              </div>
            </button>
            
            <div className="border-t border-gray-100" />
            
            <button
              onClick={exportToPDF}
              disabled={exporting !== null}
              className="w-full px-4 py-3 flex items-center space-x-3 hover:bg-gray-50 transition-colors disabled:opacity-50"
            >
              {exporting === 'pdf' ? (
                <Loader2 className="w-5 h-5 text-primary-600 animate-spin" />
              ) : (
                <FileText className="w-5 h-5 text-primary-600" />
              )}
              <div className="text-left">
                <p className="font-medium text-gray-900">Export PDF</p>
                <p className="text-xs text-gray-500">Formatted report</p>
              </div>
            </button>
          </div>
        </>
      )}
    </div>
  );
};

export default ExportButton;